### PR TITLE
[TIKA-3417] Running tika-docker as non-root user

### PR DESCRIPTION
**Pull request by ps0uth**
Adding a configurable UID:GID for the tika process to run as so it doesn't run as root. The following tests still pass after this change.

```
$ ./docker-tool.sh build 1.26
$ ./docker-tool.sh test 1.26
2be3cb0532d10f4a4efa163d856dd72738d8acd2e625a4668c270e350d7d5135
Image: apache/tika:1.26 - Passed
1.26
1.26
60411633a11e85fcfce0e1f61c34f40f0ff89dc01faae69310a2b1ca2c3ece38
Image: apache/tika:1.26-full - Passed
1.26-full
1.26-full
```

### CODE REVIEW

**Comment by ps0uth** [comment]
While going through the docker-compose samples in the repo I ran into a case or two where running as a non-root user breaks some things. For example, the compose file for ner executes a script that mutates the /ner directory, which fails because of permissions. May need to re-think some of that, like using a tmp dir.

**Comment by dameikle** [comment]
Thanks Philip. I'll have a quick look at migrating over to non-root user friendly techniques in the the docker-compose file.

**Comment by ps0uth** [comment]
Thanks and @dameikle sorry for dragging you into this. I thought I was just bugging my co-worker @lewismc with this PR. :smile:

**Comment by lewismc** [comment]
Hi @philipsoutham I will try this out and let you know what happens. Thanks

**Comment by lewismc** [comment]
@philipsoutham I can replicate the build and test results
```
404c9ade89429296fb846060d2d3f13105b6f9b1bf8d96e9998fae304470c863
Image: apache/tika:1.26 - Passed
1.26
1.26
d0bb05c60afff50ed8d6c84995984dc7d8ecd0cedce8e044f9f60470bcc4aac9
Image: apache/tika:1.26-full - Passed
1.26-full
1.26-full
```
I experienced NO issues with the docker compositions for `docker-compose-tika-customocr.yml`, `docker-compose-tika-grobid.yml` or `docker-compose-tika-ner.yml`. 

I was **UNABLE** to reproduce the issue you describe above regarding the NER example. Can you provide more detail so I can reproduce?

I did experience an issue with `docker-compose-tika-vision.yml`
```
Attaching to inception-caption_1, inception-rest_1, inception-video_1, tika_1
inception-caption_1  | INFO:tensorflow:Building model.
inception-video_1    | 2021-05-26 15:32:50.721748: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
inception-caption_1  | INFO:tensorflow:Initializing vocabulary from file: /usr/share/apache-tika/models/dl/image/caption/1M_iters_ckpt/word_counts.txt
inception-caption_1  | INFO:tensorflow:Created vocabulary with 11520 words
inception-caption_1  | 2021-05-26 15:32:51.113950: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
inception-caption_1  | INFO:tensorflow:Loading model from checkpoint: /usr/share/apache-tika/models/dl/image/caption/1M_iters_ckpt/model.ckpt-1000000
inception-caption_1  | INFO:tensorflow:Restoring parameters from /usr/share/apache-tika/models/dl/image/caption/1M_iters_ckpt/model.ckpt-1000000
inception-video_1    | ('cv2.__version__', '3.2.0')
inception-video_1    | Serving on port 8764
inception-video_1    |  * Serving Flask app "inceptionapi" (lazy loading)
inception-video_1    |  * Environment: production
inception-video_1    |    WARNING: Do not use the development server in a production environment.
inception-video_1    |    Use a production WSGI server instead.
inception-video_1    |  * Debug mode: off
inception-video_1    |  * Running on http://0.0.0.0:8764/ (Press CTRL+C to quit)
inception-caption_1  | INFO:tensorflow:Successfully loaded checkpoint: model.ckpt-1000000
inception-caption_1  | Serving on port 8764
inception-caption_1  |  * Serving Flask app "im2txtapi" (lazy loading)
inception-caption_1  |  * Environment: production
inception-caption_1  |    WARNING: Do not use the development server in a production environment.
inception-caption_1  |    Use a production WSGI server instead.
inception-caption_1  |  * Debug mode: off
inception-caption_1  |  * Running on http://0.0.0.0:8764/ (Press CTRL+C to quit)
tika_1               | May 26, 2021 3:32:53 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
tika_1               | WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
tika_1               | See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
tika_1               | for optional dependencies.
tika_1               |
tika_1               | May 26, 2021 3:32:53 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
tika_1               | WARNING: Tesseract OCR is installed and will be automatically applied to image files unless
tika_1               | you've excluded the TesseractOCRParser from the default parser.
tika_1               | Tesseract may dramatically slow down content extraction (TIKA-2359).
tika_1               | As of Tika 1.15 (and prior versions), Tesseract is automatically called.
tika_1               | In future versions of Tika, users may need to turn the TesseractOCRParser on via TikaConfig.
tika_1               | May 26, 2021 3:32:53 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
tika_1               | WARNING: org.xerial's sqlite-jdbc is not loaded.
tika_1               | Please provide the jar on your classpath to parse sqlite files.
tika_1               | See tika-parsers/pom.xml for the correct version.
tika_1               | INFO  Starting Apache Tika 1.25 server
tika_1               | INFO  Using custom config: /tika-config.xml
inception-caption_1  | 172.23.0.5 - - [26/May/2021 15:32:53] "GET /inception/v3/ping HTTP/1.1" 200 -
tika_1               | INFO  Available = true, API Status = HTTP/1.0 200 OK
tika_1               | INFO  Captions = 5, MaxCaptionLength = 15
tika_1               | INFO  Recogniser = org.apache.tika.parser.captioning.tf.TensorflowRESTCaptioner
tika_1               | INFO  Recogniser Available = true
tika_1               | INFO  Setting the server's publish address to be http://0.0.0.0:9998/
tika_1               | INFO  Logging initialized @1803ms to org.eclipse.jetty.util.log.Slf4jLog
tika_1               | INFO  jetty-9.4.33.v20201020; built: 2020-10-20T23:39:24.803Z; git: 1be68755656cef678b79a2ef1c2ebbca99e25420; jvm 14.0.2+12-Ubuntu-120.04
tika_1               | INFO  Started ServerConnector@1d8e2eea{HTTP/1.1, (http/1.1)}{0.0.0.0:9998}
tika_1               | INFO  Started @1870ms
tika_1               | WARN  Empty contextPath
tika_1               | INFO  Started o.e.j.s.h.ContextHandler@48b0e701{/,null,AVAILABLE}
tika_1               | INFO  Started Apache Tika server at http://0.0.0.0:9998/
inception-rest_1     | 2021-05-26 15:32:54.352046: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
inception-rest_1     | Can't import video libraries, No video functionality is available
inception-rest_1     | Serving on port 8764
inception-rest_1     |  * Serving Flask app "inceptionapi" (lazy loading)
inception-rest_1     |  * Environment: production
inception-rest_1     |    WARNING: Do not use the development server in a production environment.
inception-rest_1     |    Use a production WSGI server instead.
inception-rest_1     |  * Debug mode: off
inception-rest_1     |  * Running on http://0.0.0.0:8764/ (Press CTRL+C to quit)
tika_1               | WARN  Both org.apache.tika.server.resource.TikaResource#getHTML and org.apache.tika.server.resource.TikaResource#getText are equal candidates for handling the current request which can lead to unpredictable results
tika_1               | WARN  Both org.apache.tika.server.resource.TikaResource#getXML and org.apache.tika.server.resource.TikaResource#getText are equal candidates for handling the current request which can lead to unpredictable results
tika_1               | INFO  tika (application/pdf)
tika_1               | WARN  The directory /tmp has very little usable temporary space.  Operations requiring temporary files may fail.
```
When I attempt an extraction I get nothing
`curl -X PUT --data-binary @/Users/lmcgibbn/Desktop/applsci-10-01127.pdf http://localhost:9998/tika --header "Content-type: application/pdf"`

**Comment by lewismc** [comment]
[Uploading applsci-10-01127.pdf…]()

Attached file I am using for testing.

**Comment by wjwilson-ibm** [comment]
Is there a version of tika-docker that runs as non-root?

**Comment by lewismc** [comment]
@wjwilson-ibm yes literally every Docker release so far. This PR has NOT been merged yet.

**Comment by dameikle** [comment]
Sorry for not looking at this for a while @lewismc and @philipsoutham

@lewismc I think this may be my bad for the Tika Vision example. On the Tika Vision examples the Tika config only has the _ObjectRecognitionParser_ setup and in some cases restricted on the mime-types. We could extend these so the examples are less restrictive out-of-the-box.

I have the same issue for the NER example but it appear to be unrelated to this change. It's the only example that uses an entry-point script and is failing to find the class as it hasn't had the TAG env variable set.

```
tika_1  | OpenNLP models directory has files, so skipping fetch
tika_1  | Error: Could not find or load main class org.apache.tika.server.TikaServerCli
tika_1  | Caused by: java.lang.ClassNotFoundException: org.apache.tika.server.TikaServerCli
```

Adding it to the docker-compose file as a passed environment variable resolves that. Will make the change in master branch so we can sync up, then I think the PR is good to go unless any one else has other issues in their testing.

**Comment by wjwilson-ibm** [comment]
What is the status of this merge please?

**Comment by dameikle** [comment]
@wjwilson-ibm I've been using this for a bit now, so will merge this now

**Comment by dameikle** [comment]
Hello @philipsoutham and @wjwilson-ibm :wave:

I've merged this and republished the 2.1.0 and 1.27 versions on DockerHub using the updated Dockerfiles.

Thanks again for the PR, @philipsoutham :bow:

**Comment by wjwilson-ibm** [comment]
@dameikle It appears the logicalspark/docker-tikaserver:1.27 has not been updated in 4 months and the `whoami` still shows root.

**Comment by dameikle** [comment]
Hi @wjwilson-ibm. I just did the update here in apache/tika-docker. I can replicate over in logicalspark/docker-tikaserver if that would help.

**Comment by wjwilson-ibm** [comment]
@dameikle Yes to logicalspark/docker-tikaserver is our source and greatly appreciated.  Will it be a new version like 1.28 since we aren't allowed to pull latest?

**Comment by dameikle** [comment]
Hi @wjwilson-ibm :wave: 

Looks like the auto-build has been disabled on Docker Hub, so I just manually updated the 1.27 tag at logicalspark/docker-tikaserver. Can you see if this works for you please?

**Comment by wjwilson-ibm** [comment]
Hi @dameikle I can confirm the image logicalspark/docker-tikaserver:1.27 changed yesterday.  Thank you.  Unfortunately, shelling into the running container shows user root and the server running as root.  This is same as before.  See details.

```
$ docker pull logicalspark/docker-tikaserver:1.27
1.27: Pulling from logicalspark/docker-tikaserver
7b1a6ab2e44d: Pull complete 
778c5d10e7f8: Pull complete 
a47716074ba4: Pull complete 
3616900ae8b7: Pull complete 
2e227631943d: Pull complete 
bc6f84d523ee: Pull complete 
Digest: sha256:73149cc5c9f5376ade4a19d2fbf3f4d8c8ec7d219f06300cc9148df4ccc1277e
Status: Downloaded newer image for logicalspark/docker-tikaserver:1.27
docker.io/logicalspark/docker-tikaserver:1.27

$ docker run -ti logicalspark/docker-tikaserver bash
Dec 14, 2021 4:21:29 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.
Dec 14, 2021 4:21:29 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: Tesseract OCR is installed and will be automatically applied to image files unless
you've excluded the TesseractOCRParser from the default parser.
Tesseract may dramatically slow down content extraction (TIKA-2359).
As of Tika 1.15 (and prior versions), Tesseract is automatically called.
In future versions of Tika, users may need to turn the TesseractOCRParser on via TikaConfig.
Dec 14, 2021 4:21:29 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
INFO  Starting Apache Tika 1.27 server
INFO  Setting the server's publish address to be http://0.0.0.0:9998/
INFO  Logging initialized @1778ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 14.0.2+12-Ubuntu-120.04
INFO  Started ServerConnector@64beebb7{HTTP/1.1, (http/1.1)}{0.0.0.0:9998}
INFO  Started @1896ms
WARN  Empty contextPath
INFO  Started o.e.j.s.h.ContextHandler@1922e6d{/,null,AVAILABLE}
INFO  Started Apache Tika server at http://0.0.0.0:9998/

$ docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS          PORTS      NAMES
b6f4db72897a   logicalspark/docker-tikaserver   "/bin/sh -c 'exec ja…"   18 seconds ago   Up 18 seconds   9998/tcp   eager_kilby

$ docker exec -ti b6f4db72897a bash
root@b6f4db72897a:/# whoami
root

root@b6f4db72897a:/# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  3 16:21 pts/0    00:00:03 java -jar /tika-server-1.27.jar -h 0.0.0.0 bash
root        45     0  0 16:21 pts/1    00:00:00 bash
root        55    45  0 16:23 pts/1    00:00:00 ps -ef
```

**Comment by wjwilson-ibm** [comment]
Hi @dameikle I can confirm the image logicalspark/docker-tikaserver:1.28 contains the fix.  The running tika-server process is no longer running as root.  Thank you!

**Pull request merged**
